"""Deterministic (non-LLM) content required for a ScienceOpen submission:
an Abstract, Methodology, and References section rendered into review.md/
review.pdf/the HTML site, plus the scienceopen_metadata.json sidecar used
to copy-paste into ScienceOpen's manual upload form. Templated in Python
rather than generated by an LLM so this content can never suffer the
token-budget truncation failure mode fixed in the hypothesis-verdict
pipeline (see docs/superpowers/specs/2026-07-06-scienceopen-publishing-design.md).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from moonstar_physics.paper_review.review_model import ReviewData


@dataclass
class Citation:
    text: str
    url: str | None


def _join_authors(authors: list[str]) -> str:
    if len(authors) == 1:
        return authors[0]
    if len(authors) == 2:
        return f"{authors[0]} and {authors[1]}"
    return ", ".join(authors[:-1]) + f", and {authors[-1]}"


def _verdict_tally(review: ReviewData) -> str:
    if not review.hypothesis_results:
        return "no hypotheses tested"
    counts: dict[str, int] = {}
    for hr in review.hypothesis_results:
        counts[hr.verdict] = counts.get(hr.verdict, 0) + 1
    parts = [f"{count} {verdict.lower()}" for verdict, count in sorted(counts.items())]
    return ", ".join(parts)


def render_abstract(review: ReviewData) -> str:
    n = len(review.hypothesis_results)
    plural = "claim" if n == 1 else "claims"
    return (
        f"An AI-assisted hypothesis-verification review of {review.title} by {_join_authors(review.authors)}, "
        f"testing {n} curated {plural} via the Moonstar physics-hypothesis pipeline (deterministic "
        f"conservation-law/QM/dimension checks cross-examined by an LLM theory critic and devil's advocate). "
        f"Verdicts: {_verdict_tally(review)}."
    )


_METHODOLOGY_TEMPLATE = (
    "Each hypothesis is tested through Moonstar's physics_hypothesis pipeline: an LLM Extractor converts "
    "the natural-language claim into structured JSON, which is then run through four parallel deterministic "
    "checks (conservation-law, QM calculation, reference-data lookup, and dimension consistency) alongside "
    "an LLM theory critic; a devil's advocate LLM then challenges the emerging consensus; finally a "
    "synthesizer LLM produces the conversational verdict published here. Hypotheses are hand-curated by the "
    "human author before submission to the pipeline, and all pipeline output is reviewed by the author "
    "before publication.\n\n"
    "Models used: extraction with {extractor}, critique and synthesis with {critic}."
)


def render_methodology(models: dict[str, str]) -> str:
    return _METHODOLOGY_TEMPLATE.format(
        extractor=models.get("MODEL_EXTRACTOR", "unknown"),
        critic=models.get("MODEL_CRITIC", "unknown"),
    )


def format_citation(review: ReviewData) -> Citation:
    year = review.draft_date[:4] if review.draft_date else "n.d."
    return Citation(text=f"{_join_authors(review.authors)} ({year}). {review.title}.", url=review.source_url)


def _citation_line(citation: Citation) -> str:
    return f"{citation.text} {citation.url}" if citation.url else citation.text


def render_references(review: ReviewData) -> str:
    return f"## References\n\n1. {_citation_line(format_citation(review))}\n"


def build_scienceopen_metadata(
    review: ReviewData, author: dict[str, str], models: dict[str, str]
) -> dict[str, Any]:
    return {
        "submission_title": f"AI-Assisted Hypothesis Verification of {review.title}: A Moonstar Physics Review",
        "abstract": render_abstract(review),
        "authors": [author],
        "keywords": ["physics", "AI-assisted review", "hypothesis testing", "Moonstar"],
        "references": [_citation_line(format_citation(review))],
        "license_note": (
            "ScienceOpen applies CC BY 4.0 and a CrossRef DOI automatically upon acceptance — "
            "no action needed here."
        ),
        "pdf_path": f"reviews/{review.slug}/review.pdf",
    }
